version: "3"
services:
  test:
    build: ./builds/test
  preprocess:
    build: ./builds/preprocess
  bwa:
    build: ./builds/bwa
  samtools:
    build: ./builds/samtools
  notebook:
    build: ./builds/notebook
    ports:
      - "8888:8888"
